# GET http://localhost:4000/clients/1

# GET http://localhost:4000/clients/1?Jordan=9

GET http://localhost:4000/api/clients/




# POST http://localhost:4000/add
# Content-Type: application/json

# {
#     "title" : "test",
#     "id" : 1

# }